# Generated by Django 5.2.9 on 2025-12-06 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('manager', 'Менеджер'), ('seller', 'Продавец'), ('consultant', 'Консультант'), ('storekeeper', 'Кладовщик'), ('driver', 'Водитель'), ('accountant', 'Бухгалтер'), ('technician', 'Техник'), ('cleaner', 'Уборщик')], max_length=50, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оклад')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('passport_data', models.CharField(blank=True, max_length=100, verbose_name='Паспортные данные')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('morning', 'Утренняя (08:00-16:00)'), ('day', 'Дневная (12:00-20:00)'), ('evening', 'Вечерняя (16:00-00:00)'), ('night', 'Ночная (00:00-08:00)'), ('director', 'Директорская (09:00-20:00)')], max_length=20, verbose_name='Тип смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная смена')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='staff.employee', verbose_name='Сотрудник')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочие смены',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('present', 'Явка'), ('absent', 'Неявка'), ('sick', 'Больничный'), ('vacation', 'Отпуск'), ('day_off', 'Выходной'), ('late', 'Опоздание'), ('early', 'Уход раньше')], max_length=20, verbose_name='Тип явки')),
                ('actual_start', models.TimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.TimeField(blank=True, null=True, verbose_name='Фактический конец')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Отработано часов')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Сверхурочные часы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='staff.workshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Учет рабочего времени',
                'verbose_name_plural': 'Учет рабочего времени',
                'ordering': ['-work_shift__date'],
            },
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(condition=models.Q(('manager__isnull', False)), fields=('date', 'manager'), name='unique_manager_shift'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('date', 'employee'), name='unique_employee_shift'),
        ),
    ]
