# Generated by Django 5.2.9 on 2025-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='shift_type',
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(default='16:00', verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='Время начала'),
        ),
    ]
