# Generated by Django 5.2.9 on 2025-12-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Описание задачи, например: 'Подготовить отчет'.", max_length=255, verbose_name='Название задачи')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметьте, если задача завершена.', verbose_name='Выполнена')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата автоматом ставится сегодняшняя; задачи необязательно привязывать к смене.', verbose_name='Дата создания')),
                ('user', models.ForeignKey(help_text='Задачи личные для каждого пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-date', 'is_completed', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата смены, выбираемая пользователем.', verbose_name='Дата смены')),
                ('start_time', models.TimeField(default='09:00', editable=False, help_text='Фиксированное: 09:00.', verbose_name='Время начала')),
                ('end_time', models.TimeField(default='20:00', editable=False, help_text='Фиксированное: 20:00.', verbose_name='Время окончания')),
                ('user', models.ForeignKey(help_text='Смена привязана к директору/сотруднику.', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'unique_together': {('date', 'user')},
            },
        ),
    ]
