# Generated by Django 5.2.9 on 2025-12-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
