# Generated by Django 5.2.9 on 2025-12-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_stockmovement_sale_item'),
        ('staff', '0002_remove_workshift_shift_type_alter_workshift_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('financial', 'Финансовый отчет'), ('products', 'Отчет по товарам'), ('work_schedule', 'График работы'), ('daily', 'Отчет за день')], max_length=20, verbose_name='Тип отчета')),
                ('start_date', models.DateField(verbose_name='Дата с')),
                ('end_date', models.DateField(verbose_name='Дата по')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='excel', max_length=10, verbose_name='Формат')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время генерации')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Сгенерирован')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категория товаров')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='Сотрудник')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем сгенерирован')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
