# Generated by Django 5.2.9 on 2025-12-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_generated',
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('excel', 'Excel')], default='excel', max_length=10, verbose_name='Формат'),
        ),
    ]
